// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ReserveSystem.Data;

#nullable disable

namespace ReserveSystem.Data.Migrations
{
    [DbContext(typeof(ReserveSystemContext))]
    [Migration("20241118154657_JobModel")]
    partial class JobModel
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ReserveSystem.Models.JobModel", b =>
                {
                    b.Property<int>("jobID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("jobID"));

                    b.Property<int?>("JobModeljobID")
                        .HasColumnType("int");

                    b.Property<string>("jobDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("jobID");

                    b.HasIndex("JobModeljobID");

                    b.ToTable("JobModel");
                });

            modelBuilder.Entity("ReserveSystem.Models.JobModel", b =>
                {
                    b.HasOne("ReserveSystem.Models.JobModel", null)
                        .WithMany("jobName")
                        .HasForeignKey("JobModeljobID");
                });

            modelBuilder.Entity("ReserveSystem.Models.JobModel", b =>
                {
                    b.Navigation("jobName");
                });
#pragma warning restore 612, 618
        }
    }
}
