// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ReserveSystem.Data;

#nullable disable

namespace ReserveSystem.Data.Migrations
{
    [DbContext(typeof(ReserveSystemContext))]
    [Migration("20250106220556_AddData3")]
    partial class AddData3
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ReserveSystem.Models.MotoristaTransporte", b =>
                {
                    b.Property<int>("MotoristaTransporteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MotoristaTransporteId"));

                    b.Property<int>("StaffId")
                        .HasColumnType("int");

                    b.Property<int>("TransporteId")
                        .HasColumnType("int");

                    b.HasKey("MotoristaTransporteId");

                    b.HasIndex("StaffId");

                    b.HasIndex("TransporteId");

                    b.ToTable("MotoristaTransporte");
                });

            modelBuilder.Entity("ReserveSystem.Models.Staff", b =>
                {
                    b.Property<int>("StaffId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StaffId"));

                    b.Property<string>("Job_Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Staff_Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TipoCarta")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("StaffId");

                    b.ToTable("Staff");

                    b.HasData(
                        new
                        {
                            StaffId = 26,
                            Job_Name = "Motorista",
                            Staff_Name = "João Silva",
                            TipoCarta = "C"
                        },
                        new
                        {
                            StaffId = 27,
                            Job_Name = "Guia Turístico",
                            Staff_Name = "Maria Ferreira"
                        },
                        new
                        {
                            StaffId = 28,
                            Job_Name = "Motorista",
                            Staff_Name = "Carlos Mendes",
                            TipoCarta = "D"
                        },
                        new
                        {
                            StaffId = 29,
                            Job_Name = "Gestor de Excursão",
                            Staff_Name = "Ana Costa"
                        },
                        new
                        {
                            StaffId = 30,
                            Job_Name = "Motorista",
                            Staff_Name = "Luís Pereira",
                            TipoCarta = "C+E"
                        },
                        new
                        {
                            StaffId = 31,
                            Job_Name = "Guia Turístico",
                            Staff_Name = "Rita Oliveira"
                        },
                        new
                        {
                            StaffId = 32,
                            Job_Name = "Motorista",
                            Staff_Name = "Pedro Santos",
                            TipoCarta = "B"
                        },
                        new
                        {
                            StaffId = 33,
                            Job_Name = "Gestor de Excursão",
                            Staff_Name = "Marta Lopes"
                        },
                        new
                        {
                            StaffId = 34,
                            Job_Name = "Motorista",
                            Staff_Name = "Fernando Gomes",
                            TipoCarta = "D+E"
                        },
                        new
                        {
                            StaffId = 35,
                            Job_Name = "Guia Turístico",
                            Staff_Name = "Cláudia Neves"
                        },
                        new
                        {
                            StaffId = 36,
                            Job_Name = "Motorista",
                            Staff_Name = "António Silva",
                            TipoCarta = "C"
                        },
                        new
                        {
                            StaffId = 37,
                            Job_Name = "Gestor de Excursão",
                            Staff_Name = "Beatriz Sousa"
                        },
                        new
                        {
                            StaffId = 38,
                            Job_Name = "Motorista",
                            Staff_Name = "Ricardo Teixeira",
                            TipoCarta = "D"
                        },
                        new
                        {
                            StaffId = 39,
                            Job_Name = "Guia Turístico",
                            Staff_Name = "Joana Martins"
                        },
                        new
                        {
                            StaffId = 40,
                            Job_Name = "Motorista",
                            Staff_Name = "Tiago Rocha",
                            TipoCarta = "C+E"
                        },
                        new
                        {
                            StaffId = 41,
                            Job_Name = "Gestor de Excursão",
                            Staff_Name = "Helena Ribeiro"
                        },
                        new
                        {
                            StaffId = 42,
                            Job_Name = "Motorista",
                            Staff_Name = "José Almeida",
                            TipoCarta = "B"
                        },
                        new
                        {
                            StaffId = 43,
                            Job_Name = "Guia Turístico",
                            Staff_Name = "Sofia Silva"
                        },
                        new
                        {
                            StaffId = 44,
                            Job_Name = "Motorista",
                            Staff_Name = "Vítor Pinto",
                            TipoCarta = "C"
                        },
                        new
                        {
                            StaffId = 45,
                            Job_Name = "Gestor de Excursão",
                            Staff_Name = "Catarina Azevedo"
                        },
                        new
                        {
                            StaffId = 46,
                            Job_Name = "Motorista",
                            Staff_Name = "André Matos",
                            TipoCarta = "D+E"
                        },
                        new
                        {
                            StaffId = 47,
                            Job_Name = "Guia Turístico",
                            Staff_Name = "Patrícia Lima"
                        },
                        new
                        {
                            StaffId = 48,
                            Job_Name = "Motorista",
                            Staff_Name = "Eduardo Nunes",
                            TipoCarta = "B"
                        },
                        new
                        {
                            StaffId = 49,
                            Job_Name = "Gestor de Excursão",
                            Staff_Name = "Carla Moreira"
                        },
                        new
                        {
                            StaffId = 50,
                            Job_Name = "Motorista",
                            Staff_Name = "Bruno Tavares",
                            TipoCarta = "C"
                        });
                });

            modelBuilder.Entity("ReserveSystem.Models.Transporte", b =>
                {
                    b.Property<int>("TransporteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TransporteId"));

                    b.Property<int>("AnoFabricacao")
                        .HasColumnType("int");

                    b.Property<int>("Capacidade")
                        .HasColumnType("int");

                    b.Property<string>("CartaTransporte")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DescricaoTipoTransporte")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Matricula")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("TipoTransporte")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("TransporteId");

                    b.ToTable("Transporte");
                });

            modelBuilder.Entity("ReserveSystem.Models.MotoristaTransporte", b =>
                {
                    b.HasOne("ReserveSystem.Models.Staff", "Staff")
                        .WithMany("MotoristaTransporte")
                        .HasForeignKey("StaffId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ReserveSystem.Models.Transporte", "Transporte")
                        .WithMany("MotoristaTransporte")
                        .HasForeignKey("TransporteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Staff");

                    b.Navigation("Transporte");
                });

            modelBuilder.Entity("ReserveSystem.Models.Staff", b =>
                {
                    b.Navigation("MotoristaTransporte");
                });

            modelBuilder.Entity("ReserveSystem.Models.Transporte", b =>
                {
                    b.Navigation("MotoristaTransporte");
                });
#pragma warning restore 612, 618
        }
    }
}
