// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ReserveSystem.Data;

#nullable disable

namespace ReserveSystem.Data.Migrations
{
    [DbContext(typeof(ReserveSystemContext))]
    [Migration("20250106222101_AddDataMotoristaTransporte")]
    partial class AddDataMotoristaTransporte
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ReserveSystem.Models.MotoristaTransporte", b =>
                {
                    b.Property<int>("MotoristaTransporteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MotoristaTransporteId"));

                    b.Property<int>("StaffId")
                        .HasColumnType("int");

                    b.Property<int>("TransporteId")
                        .HasColumnType("int");

                    b.HasKey("MotoristaTransporteId");

                    b.HasIndex("StaffId");

                    b.HasIndex("TransporteId");

                    b.ToTable("MotoristaTransporte");

                    b.HasData(
                        new
                        {
                            MotoristaTransporteId = 26,
                            StaffId = 26,
                            TransporteId = 26
                        },
                        new
                        {
                            MotoristaTransporteId = 27,
                            StaffId = 27,
                            TransporteId = 27
                        },
                        new
                        {
                            MotoristaTransporteId = 28,
                            StaffId = 28,
                            TransporteId = 28
                        },
                        new
                        {
                            MotoristaTransporteId = 29,
                            StaffId = 29,
                            TransporteId = 29
                        },
                        new
                        {
                            MotoristaTransporteId = 30,
                            StaffId = 30,
                            TransporteId = 30
                        },
                        new
                        {
                            MotoristaTransporteId = 31,
                            StaffId = 31,
                            TransporteId = 31
                        },
                        new
                        {
                            MotoristaTransporteId = 32,
                            StaffId = 32,
                            TransporteId = 32
                        },
                        new
                        {
                            MotoristaTransporteId = 33,
                            StaffId = 33,
                            TransporteId = 33
                        },
                        new
                        {
                            MotoristaTransporteId = 34,
                            StaffId = 34,
                            TransporteId = 34
                        },
                        new
                        {
                            MotoristaTransporteId = 35,
                            StaffId = 35,
                            TransporteId = 35
                        },
                        new
                        {
                            MotoristaTransporteId = 36,
                            StaffId = 36,
                            TransporteId = 36
                        },
                        new
                        {
                            MotoristaTransporteId = 37,
                            StaffId = 37,
                            TransporteId = 37
                        },
                        new
                        {
                            MotoristaTransporteId = 38,
                            StaffId = 38,
                            TransporteId = 38
                        },
                        new
                        {
                            MotoristaTransporteId = 39,
                            StaffId = 39,
                            TransporteId = 39
                        },
                        new
                        {
                            MotoristaTransporteId = 40,
                            StaffId = 40,
                            TransporteId = 40
                        },
                        new
                        {
                            MotoristaTransporteId = 41,
                            StaffId = 41,
                            TransporteId = 41
                        },
                        new
                        {
                            MotoristaTransporteId = 42,
                            StaffId = 42,
                            TransporteId = 42
                        },
                        new
                        {
                            MotoristaTransporteId = 43,
                            StaffId = 43,
                            TransporteId = 43
                        },
                        new
                        {
                            MotoristaTransporteId = 44,
                            StaffId = 44,
                            TransporteId = 44
                        },
                        new
                        {
                            MotoristaTransporteId = 45,
                            StaffId = 45,
                            TransporteId = 45
                        },
                        new
                        {
                            MotoristaTransporteId = 46,
                            StaffId = 46,
                            TransporteId = 46
                        },
                        new
                        {
                            MotoristaTransporteId = 47,
                            StaffId = 47,
                            TransporteId = 47
                        },
                        new
                        {
                            MotoristaTransporteId = 48,
                            StaffId = 48,
                            TransporteId = 48
                        },
                        new
                        {
                            MotoristaTransporteId = 49,
                            StaffId = 49,
                            TransporteId = 49
                        },
                        new
                        {
                            MotoristaTransporteId = 50,
                            StaffId = 50,
                            TransporteId = 50
                        });
                });

            modelBuilder.Entity("ReserveSystem.Models.Staff", b =>
                {
                    b.Property<int>("StaffId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StaffId"));

                    b.Property<string>("Job_Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Staff_Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TipoCarta")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("StaffId");

                    b.ToTable("Staff");

                    b.HasData(
                        new
                        {
                            StaffId = 26,
                            Job_Name = "Motorista",
                            Staff_Name = "João Silva",
                            TipoCarta = "C"
                        },
                        new
                        {
                            StaffId = 27,
                            Job_Name = "Guia Turístico",
                            Staff_Name = "Maria Ferreira"
                        },
                        new
                        {
                            StaffId = 28,
                            Job_Name = "Motorista",
                            Staff_Name = "Carlos Mendes",
                            TipoCarta = "D"
                        },
                        new
                        {
                            StaffId = 29,
                            Job_Name = "Gestor de Excursão",
                            Staff_Name = "Ana Costa"
                        },
                        new
                        {
                            StaffId = 30,
                            Job_Name = "Motorista",
                            Staff_Name = "Luís Pereira",
                            TipoCarta = "C+E"
                        },
                        new
                        {
                            StaffId = 31,
                            Job_Name = "Guia Turístico",
                            Staff_Name = "Rita Oliveira"
                        },
                        new
                        {
                            StaffId = 32,
                            Job_Name = "Motorista",
                            Staff_Name = "Pedro Santos",
                            TipoCarta = "B"
                        },
                        new
                        {
                            StaffId = 33,
                            Job_Name = "Gestor de Excursão",
                            Staff_Name = "Marta Lopes"
                        },
                        new
                        {
                            StaffId = 34,
                            Job_Name = "Motorista",
                            Staff_Name = "Fernando Gomes",
                            TipoCarta = "D+E"
                        },
                        new
                        {
                            StaffId = 35,
                            Job_Name = "Guia Turístico",
                            Staff_Name = "Cláudia Neves"
                        },
                        new
                        {
                            StaffId = 36,
                            Job_Name = "Motorista",
                            Staff_Name = "António Silva",
                            TipoCarta = "C"
                        },
                        new
                        {
                            StaffId = 37,
                            Job_Name = "Gestor de Excursão",
                            Staff_Name = "Beatriz Sousa"
                        },
                        new
                        {
                            StaffId = 38,
                            Job_Name = "Motorista",
                            Staff_Name = "Ricardo Teixeira",
                            TipoCarta = "D"
                        },
                        new
                        {
                            StaffId = 39,
                            Job_Name = "Guia Turístico",
                            Staff_Name = "Joana Martins"
                        },
                        new
                        {
                            StaffId = 40,
                            Job_Name = "Motorista",
                            Staff_Name = "Tiago Rocha",
                            TipoCarta = "C+E"
                        },
                        new
                        {
                            StaffId = 41,
                            Job_Name = "Gestor de Excursão",
                            Staff_Name = "Helena Ribeiro"
                        },
                        new
                        {
                            StaffId = 42,
                            Job_Name = "Motorista",
                            Staff_Name = "José Almeida",
                            TipoCarta = "B"
                        },
                        new
                        {
                            StaffId = 43,
                            Job_Name = "Guia Turístico",
                            Staff_Name = "Sofia Silva"
                        },
                        new
                        {
                            StaffId = 44,
                            Job_Name = "Motorista",
                            Staff_Name = "Vítor Pinto",
                            TipoCarta = "C"
                        },
                        new
                        {
                            StaffId = 45,
                            Job_Name = "Gestor de Excursão",
                            Staff_Name = "Catarina Azevedo"
                        },
                        new
                        {
                            StaffId = 46,
                            Job_Name = "Motorista",
                            Staff_Name = "André Matos",
                            TipoCarta = "D+E"
                        },
                        new
                        {
                            StaffId = 47,
                            Job_Name = "Guia Turístico",
                            Staff_Name = "Patrícia Lima"
                        },
                        new
                        {
                            StaffId = 48,
                            Job_Name = "Motorista",
                            Staff_Name = "Eduardo Nunes",
                            TipoCarta = "B"
                        },
                        new
                        {
                            StaffId = 49,
                            Job_Name = "Gestor de Excursão",
                            Staff_Name = "Carla Moreira"
                        },
                        new
                        {
                            StaffId = 50,
                            Job_Name = "Motorista",
                            Staff_Name = "Bruno Tavares",
                            TipoCarta = "C"
                        });
                });

            modelBuilder.Entity("ReserveSystem.Models.Transporte", b =>
                {
                    b.Property<int>("TransporteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TransporteId"));

                    b.Property<int>("AnoFabricacao")
                        .HasColumnType("int");

                    b.Property<int>("Capacidade")
                        .HasColumnType("int");

                    b.Property<string>("CartaTransporte")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DescricaoTipoTransporte")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Matricula")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("TipoTransporte")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("TransporteId");

                    b.ToTable("Transporte");

                    b.HasData(
                        new
                        {
                            TransporteId = 26,
                            AnoFabricacao = 2015,
                            Capacidade = 55,
                            CartaTransporte = "D",
                            DescricaoTipoTransporte = "Autocarro confortável para turismo de longa distância",
                            Matricula = "AA-1234",
                            TipoTransporte = "Autocarro"
                        },
                        new
                        {
                            TransporteId = 27,
                            AnoFabricacao = 2019,
                            Capacidade = 20,
                            CartaTransporte = "D",
                            DescricaoTipoTransporte = "Minibus ideal para grupos pequenos em excursões",
                            Matricula = "BB-5678",
                            TipoTransporte = "Minibus"
                        },
                        new
                        {
                            TransporteId = 28,
                            AnoFabricacao = 2021,
                            Capacidade = 12,
                            CartaTransporte = "C",
                            DescricaoTipoTransporte = "Van moderna para transporte rápido de passageiros",
                            Matricula = "CC-9101",
                            TipoTransporte = "Van"
                        },
                        new
                        {
                            TransporteId = 29,
                            AnoFabricacao = 2016,
                            Capacidade = 45,
                            CartaTransporte = "D",
                            DescricaoTipoTransporte = "Autocarro com ar condicionado e Wi-Fi",
                            Matricula = "DD-1122",
                            TipoTransporte = "Autocarro"
                        },
                        new
                        {
                            TransporteId = 30,
                            AnoFabricacao = 2020,
                            Capacidade = 18,
                            CartaTransporte = "C",
                            DescricaoTipoTransporte = "Van prática para transporte urbano",
                            Matricula = "EE-3344",
                            TipoTransporte = "Van"
                        },
                        new
                        {
                            TransporteId = 31,
                            AnoFabricacao = 2017,
                            Capacidade = 35,
                            CartaTransporte = "D",
                            DescricaoTipoTransporte = "Minibus económico com espaço para bagagens",
                            Matricula = "FF-5566",
                            TipoTransporte = "Minibus"
                        },
                        new
                        {
                            TransporteId = 32,
                            AnoFabricacao = 2013,
                            Capacidade = 60,
                            CartaTransporte = "D",
                            DescricaoTipoTransporte = "Autocarro de grande capacidade para excursões escolares",
                            Matricula = "GG-7788",
                            TipoTransporte = "Autocarro"
                        },
                        new
                        {
                            TransporteId = 33,
                            AnoFabricacao = 2022,
                            Capacidade = 14,
                            CartaTransporte = "B",
                            DescricaoTipoTransporte = "Van recente e equipada para transporte eficiente",
                            Matricula = "HH-9900",
                            TipoTransporte = "Van"
                        },
                        new
                        {
                            TransporteId = 34,
                            AnoFabricacao = 2014,
                            Capacidade = 50,
                            CartaTransporte = "D",
                            DescricaoTipoTransporte = "Autocarro clássico para transporte turístico",
                            Matricula = "II-2233",
                            TipoTransporte = "Autocarro"
                        },
                        new
                        {
                            TransporteId = 35,
                            AnoFabricacao = 2018,
                            Capacidade = 22,
                            CartaTransporte = "D",
                            DescricaoTipoTransporte = "Minibus compacto para serviços personalizados",
                            Matricula = "JJ-4455",
                            TipoTransporte = "Minibus"
                        },
                        new
                        {
                            TransporteId = 36,
                            AnoFabricacao = 2015,
                            Capacidade = 55,
                            CartaTransporte = "D",
                            DescricaoTipoTransporte = "Autocarro espaçoso para grandes eventos",
                            Matricula = "KK-6677",
                            TipoTransporte = "Autocarro"
                        },
                        new
                        {
                            TransporteId = 37,
                            AnoFabricacao = 2021,
                            Capacidade = 10,
                            CartaTransporte = "B",
                            DescricaoTipoTransporte = "Van ágil para serviços de transporte rápidos",
                            Matricula = "LL-8899",
                            TipoTransporte = "Van"
                        },
                        new
                        {
                            TransporteId = 38,
                            AnoFabricacao = 2017,
                            Capacidade = 48,
                            CartaTransporte = "D",
                            DescricaoTipoTransporte = "Autocarro ideal para rotas intermunicipais",
                            Matricula = "MM-0011",
                            TipoTransporte = "Autocarro"
                        },
                        new
                        {
                            TransporteId = 39,
                            AnoFabricacao = 2019,
                            Capacidade = 28,
                            CartaTransporte = "D",
                            DescricaoTipoTransporte = "Minibus com sistema de climatização",
                            Matricula = "NN-1123",
                            TipoTransporte = "Minibus"
                        },
                        new
                        {
                            TransporteId = 40,
                            AnoFabricacao = 2016,
                            Capacidade = 40,
                            CartaTransporte = "D",
                            DescricaoTipoTransporte = "Autocarro para transporte corporativo",
                            Matricula = "OO-4456",
                            TipoTransporte = "Autocarro"
                        },
                        new
                        {
                            TransporteId = 41,
                            AnoFabricacao = 2020,
                            Capacidade = 16,
                            CartaTransporte = "C",
                            DescricaoTipoTransporte = "Van prática para pequenas viagens",
                            Matricula = "PP-7789",
                            TipoTransporte = "Van"
                        },
                        new
                        {
                            TransporteId = 42,
                            AnoFabricacao = 2015,
                            Capacidade = 35,
                            CartaTransporte = "D",
                            DescricaoTipoTransporte = "Minibus económico com bancos confortáveis",
                            Matricula = "QQ-9901",
                            TipoTransporte = "Minibus"
                        },
                        new
                        {
                            TransporteId = 43,
                            AnoFabricacao = 2013,
                            Capacidade = 60,
                            CartaTransporte = "D",
                            DescricaoTipoTransporte = "Autocarro com assentos reclináveis",
                            Matricula = "RR-2234",
                            TipoTransporte = "Autocarro"
                        },
                        new
                        {
                            TransporteId = 44,
                            AnoFabricacao = 2022,
                            Capacidade = 12,
                            CartaTransporte = "B",
                            DescricaoTipoTransporte = "Van eficiente para transporte diário",
                            Matricula = "SS-5567",
                            TipoTransporte = "Van"
                        },
                        new
                        {
                            TransporteId = 45,
                            AnoFabricacao = 2021,
                            Capacidade = 25,
                            CartaTransporte = "D",
                            DescricaoTipoTransporte = "Minibus recente para excursões de lazer",
                            Matricula = "TT-7789",
                            TipoTransporte = "Minibus"
                        },
                        new
                        {
                            TransporteId = 46,
                            AnoFabricacao = 2016,
                            Capacidade = 45,
                            CartaTransporte = "D",
                            DescricaoTipoTransporte = "Autocarro equipado com Wi-Fi",
                            Matricula = "UU-9902",
                            TipoTransporte = "Autocarro"
                        },
                        new
                        {
                            TransporteId = 47,
                            AnoFabricacao = 2020,
                            Capacidade = 18,
                            CartaTransporte = "C",
                            DescricaoTipoTransporte = "Van espaçosa para famílias",
                            Matricula = "VV-2235",
                            TipoTransporte = "Van"
                        },
                        new
                        {
                            TransporteId = 48,
                            AnoFabricacao = 2014,
                            Capacidade = 50,
                            CartaTransporte = "D",
                            DescricaoTipoTransporte = "Autocarro ideal para viagens de longa distância",
                            Matricula = "WW-4457",
                            TipoTransporte = "Autocarro"
                        },
                        new
                        {
                            TransporteId = 49,
                            AnoFabricacao = 2018,
                            Capacidade = 30,
                            CartaTransporte = "D",
                            DescricaoTipoTransporte = "Minibus para transporte escolar",
                            Matricula = "XX-6678",
                            TipoTransporte = "Minibus"
                        },
                        new
                        {
                            TransporteId = 50,
                            AnoFabricacao = 2021,
                            Capacidade = 14,
                            CartaTransporte = "B",
                            DescricaoTipoTransporte = "Van para serviços de transporte rápidos e eficientes",
                            Matricula = "YY-8890",
                            TipoTransporte = "Van"
                        });
                });

            modelBuilder.Entity("ReserveSystem.Models.MotoristaTransporte", b =>
                {
                    b.HasOne("ReserveSystem.Models.Staff", "Staff")
                        .WithMany("MotoristaTransporte")
                        .HasForeignKey("StaffId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ReserveSystem.Models.Transporte", "Transporte")
                        .WithMany("MotoristaTransporte")
                        .HasForeignKey("TransporteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Staff");

                    b.Navigation("Transporte");
                });

            modelBuilder.Entity("ReserveSystem.Models.Staff", b =>
                {
                    b.Navigation("MotoristaTransporte");
                });

            modelBuilder.Entity("ReserveSystem.Models.Transporte", b =>
                {
                    b.Navigation("MotoristaTransporte");
                });
#pragma warning restore 612, 618
        }
    }
}
