// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ReserveSystem.Data;

#nullable disable

namespace ReserveSystem.Migrations
{
    [DbContext(typeof(ReserveSystemContext))]
    [Migration("20241120132533_AddValidations")]
    partial class AddValidations
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0");

            modelBuilder.Entity("ReserveSystem.Models.RoomServiceBooking", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("BookedState")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("bit");

                    b.Property<int>("ClientFeedback")
                        .HasColumnType("INTEGER(1)");

                    b.Property<int>("ClientId")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("INTEGER(11)");

                    b.Property<DateTime>("DateTime")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime");

                    b.Property<DateOnly>("EndDate")
                        .HasColumnType("date");

                    b.Property<bool>("PaymentDone")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("bit");

                    b.Property<int>("RoomId")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("INTEGER");

                    b.Property<int>("RoomServiceId")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("INTEGER(11)");

                    b.Property<bool>("StaffConfirmation")
                        .HasColumnType("bit");

                    b.Property<int>("StaffId")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("INTEGER(11)");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date");

                    b.Property<decimal>("ValueToPay")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("decimal(8, 2)");

                    b.HasKey("Id");

                    b.ToTable("RoomServiceBooking");
                });
#pragma warning restore 612, 618
        }
    }
}
