// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ReserveSystem.Data;

#nullable disable

namespace ReserveSystem.Migrations
{
    [DbContext(typeof(ReserveSystemContext))]
    [Migration("20241211094311_ExcursaoFavoritaCreated")]
    partial class ExcursaoFavoritaCreated
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ReserveSystem.Models.ClienteTestModel", b =>
                {
                    b.Property<int>("ClienteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ClienteId"));

                    b.Property<DateTime>("DataNascimento")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Telefone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ClienteId");

                    b.ToTable("ClienteTestModel");

                    b.HasData(
                        new
                        {
                            ClienteId = 21,
                            DataNascimento = new DateTime(1985, 5, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "carlos.silva@email.com",
                            Nome = "Carlos Silva",
                            Telefone = "923412453"
                        },
                        new
                        {
                            ClienteId = 22,
                            DataNascimento = new DateTime(1990, 8, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "ana.oliveira@email.com",
                            Nome = "Ana Oliveira",
                            Telefone = "998765432"
                        },
                        new
                        {
                            ClienteId = 23,
                            DataNascimento = new DateTime(1982, 3, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "joao.pereira@email.com",
                            Nome = "João Pereira",
                            Telefone = "987654321"
                        },
                        new
                        {
                            ClienteId = 24,
                            DataNascimento = new DateTime(1978, 11, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "maria.souza@email.com",
                            Nome = "Maria Souza",
                            Telefone = "996543210"
                        },
                        new
                        {
                            ClienteId = 25,
                            DataNascimento = new DateTime(1993, 7, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "lucas.costa@email.com",
                            Nome = "Lucas Costa",
                            Telefone = "934567890"
                        },
                        new
                        {
                            ClienteId = 26,
                            DataNascimento = new DateTime(1989, 10, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "isabela.almeida@email.com",
                            Nome = "Isabela Almeida",
                            Telefone = "945678901"
                        },
                        new
                        {
                            ClienteId = 27,
                            DataNascimento = new DateTime(1995, 2, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "felipe.rocha@email.com",
                            Nome = "Felipe Rocha",
                            Telefone = "923456789"
                        },
                        new
                        {
                            ClienteId = 28,
                            DataNascimento = new DateTime(1983, 4, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "carla.martins@email.com",
                            Nome = "Carla Martins",
                            Telefone = "911223344"
                        },
                        new
                        {
                            ClienteId = 29,
                            DataNascimento = new DateTime(1990, 12, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "fernando.gomes@email.com",
                            Nome = "Fernando Gomes",
                            Telefone = "997654321"
                        },
                        new
                        {
                            ClienteId = 30,
                            DataNascimento = new DateTime(1988, 9, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "beatriz.santos@email.com",
                            Nome = "Beatriz Santos",
                            Telefone = "968754321"
                        },
                        new
                        {
                            ClienteId = 31,
                            DataNascimento = new DateTime(1992, 1, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "ricardo.ferreira@email.com",
                            Nome = "Ricardo Ferreira",
                            Telefone = "954321098"
                        },
                        new
                        {
                            ClienteId = 32,
                            DataNascimento = new DateTime(1994, 6, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "juliana.silva@email.com",
                            Nome = "Juliana Silva",
                            Telefone = "924567890"
                        },
                        new
                        {
                            ClienteId = 33,
                            DataNascimento = new DateTime(1987, 5, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "gabriel.lima@email.com",
                            Nome = "Gabriel Lima",
                            Telefone = "917654321"
                        },
                        new
                        {
                            ClienteId = 34,
                            DataNascimento = new DateTime(1991, 11, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "mariana.costa@email.com",
                            Nome = "Mariana Costa",
                            Telefone = "935678902"
                        },
                        new
                        {
                            ClienteId = 35,
                            DataNascimento = new DateTime(1980, 2, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "vitor.hugo@email.com",
                            Nome = "Vitor Hugo",
                            Telefone = "945678901"
                        },
                        new
                        {
                            ClienteId = 36,
                            DataNascimento = new DateTime(1994, 12, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "larissa.oliveira@email.com",
                            Nome = "Larissa Oliveira",
                            Telefone = "923456788"
                        },
                        new
                        {
                            ClienteId = 37,
                            DataNascimento = new DateTime(1993, 1, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "rafael.souza@email.com",
                            Nome = "Rafael Souza",
                            Telefone = "999887777"
                        },
                        new
                        {
                            ClienteId = 38,
                            DataNascimento = new DateTime(1986, 4, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "paula.dias@email.com",
                            Nome = "Paula Dias",
                            Telefone = "912345678"
                        },
                        new
                        {
                            ClienteId = 39,
                            DataNascimento = new DateTime(1992, 8, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "eduardo.rocha@email.com",
                            Nome = "Eduardo Rocha",
                            Telefone = "923456788"
                        },
                        new
                        {
                            ClienteId = 40,
                            DataNascimento = new DateTime(1984, 10, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "tatiane.santos@email.com",
                            Nome = "Tatiane Santos",
                            Telefone = "943567890"
                        });
                });

            modelBuilder.Entity("ReserveSystem.Models.ExcursaoFavoritaModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ClienteId")
                        .HasColumnType("int");

                    b.Property<string>("Comentario")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ExcursaoId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ClienteId");

                    b.HasIndex("ExcursaoId");

                    b.ToTable("ExcursaoFavoritaModel");
                });

            modelBuilder.Entity("ReserveSystem.Models.ExcursaoModel", b =>
                {
                    b.Property<int>("Excursao_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Excursao_Id"));

                    b.Property<DateTime>("Data_Fim")
                        .HasColumnType("DATETIME");

                    b.Property<DateTime>("Data_Inicio")
                        .HasColumnType("DATETIME");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Preco")
                        .HasColumnType("DECIMAL");

                    b.Property<int>("Staff_Id")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Excursao_Id");

                    b.ToTable("ExcursaoModel");

                    b.HasData(
                        new
                        {
                            Excursao_Id = 20,
                            Data_Fim = new DateTime(2024, 12, 13, 9, 43, 11, 363, DateTimeKind.Utc).AddTicks(2601),
                            Data_Inicio = new DateTime(2024, 12, 12, 9, 43, 11, 363, DateTimeKind.Utc).AddTicks(2584),
                            Descricao = "Exploração cultural pela cidade",
                            Preco = 50.0m,
                            Staff_Id = 1,
                            Titulo = "Tour pela Cidade"
                        },
                        new
                        {
                            Excursao_Id = 21,
                            Data_Fim = new DateTime(2024, 12, 14, 13, 43, 11, 363, DateTimeKind.Utc).AddTicks(2607),
                            Data_Inicio = new DateTime(2024, 12, 14, 9, 43, 11, 363, DateTimeKind.Utc).AddTicks(2606),
                            Descricao = "Passeio pelas águas tranquilas",
                            Preco = 80.0m,
                            Staff_Id = 2,
                            Titulo = "Passeio de Barco"
                        },
                        new
                        {
                            Excursao_Id = 22,
                            Data_Fim = new DateTime(2024, 12, 16, 15, 43, 11, 363, DateTimeKind.Utc).AddTicks(2609),
                            Data_Inicio = new DateTime(2024, 12, 16, 9, 43, 11, 363, DateTimeKind.Utc).AddTicks(2608),
                            Descricao = "Uma aventura entre as montanhas",
                            Preco = 120.0m,
                            Staff_Id = 3,
                            Titulo = "Caminhada na Montanha"
                        },
                        new
                        {
                            Excursao_Id = 23,
                            Data_Fim = new DateTime(2024, 12, 17, 12, 43, 11, 363, DateTimeKind.Utc).AddTicks(2611),
                            Data_Inicio = new DateTime(2024, 12, 17, 9, 43, 11, 363, DateTimeKind.Utc).AddTicks(2610),
                            Descricao = "Caminhada e observação da fauna e flora do parque",
                            Preco = 40.0m,
                            Staff_Id = 4,
                            Titulo = "Passeio no Parque"
                        },
                        new
                        {
                            Excursao_Id = 24,
                            Data_Fim = new DateTime(2024, 12, 18, 14, 43, 11, 363, DateTimeKind.Utc).AddTicks(2612),
                            Data_Inicio = new DateTime(2024, 12, 18, 9, 43, 11, 363, DateTimeKind.Utc).AddTicks(2612),
                            Descricao = "Exploração subaquática em recifes de corais",
                            Preco = 150.0m,
                            Staff_Id = 5,
                            Titulo = "Aventura Subaquática"
                        },
                        new
                        {
                            Excursao_Id = 25,
                            Data_Fim = new DateTime(2024, 12, 19, 12, 43, 11, 363, DateTimeKind.Utc).AddTicks(2614),
                            Data_Inicio = new DateTime(2024, 12, 19, 9, 43, 11, 363, DateTimeKind.Utc).AddTicks(2614),
                            Descricao = "Uma experiência única para ver o mundo de cima",
                            Preco = 200.0m,
                            Staff_Id = 6,
                            Titulo = "Passeio de Balão"
                        },
                        new
                        {
                            Excursao_Id = 26,
                            Data_Fim = new DateTime(2024, 12, 20, 15, 43, 11, 363, DateTimeKind.Utc).AddTicks(2616),
                            Data_Inicio = new DateTime(2024, 12, 20, 9, 43, 11, 363, DateTimeKind.Utc).AddTicks(2616),
                            Descricao = "Tour por vinícolas e degustação de vinhos finos",
                            Preco = 120.0m,
                            Staff_Id = 7,
                            Titulo = "Rota dos Vinhos"
                        },
                        new
                        {
                            Excursao_Id = 27,
                            Data_Fim = new DateTime(2024, 12, 21, 17, 43, 11, 363, DateTimeKind.Utc).AddTicks(2620),
                            Data_Inicio = new DateTime(2024, 12, 21, 9, 43, 11, 363, DateTimeKind.Utc).AddTicks(2618),
                            Descricao = "Aventura no deserto com passeio de camelo e visita a oásis",
                            Preco = 250.0m,
                            Staff_Id = 8,
                            Titulo = "Expedição ao Deserto"
                        },
                        new
                        {
                            Excursao_Id = 28,
                            Data_Fim = new DateTime(2024, 12, 22, 21, 43, 11, 363, DateTimeKind.Utc).AddTicks(2622),
                            Data_Inicio = new DateTime(2024, 12, 22, 9, 43, 11, 363, DateTimeKind.Utc).AddTicks(2621),
                            Descricao = "Safari em reserva natural com guia especializado",
                            Preco = 500.00m,
                            Staff_Id = 9,
                            Titulo = "Safari na África"
                        },
                        new
                        {
                            Excursao_Id = 29,
                            Data_Fim = new DateTime(2024, 12, 23, 19, 43, 11, 363, DateTimeKind.Utc).AddTicks(2624),
                            Data_Inicio = new DateTime(2024, 12, 23, 9, 43, 11, 363, DateTimeKind.Utc).AddTicks(2623),
                            Descricao = "Aventura no Ártico para ver as luzes do norte",
                            Preco = 350.0m,
                            Staff_Id = 10,
                            Titulo = "Expedição Polar"
                        },
                        new
                        {
                            Excursao_Id = 30,
                            Data_Fim = new DateTime(2024, 12, 24, 18, 43, 11, 363, DateTimeKind.Utc).AddTicks(2626),
                            Data_Inicio = new DateTime(2024, 12, 24, 9, 43, 11, 363, DateTimeKind.Utc).AddTicks(2625),
                            Descricao = "Exploração pela floresta amazônica com guias especializados",
                            Preco = 180.0m,
                            Staff_Id = 11,
                            Titulo = "Trekking na Amazônia"
                        },
                        new
                        {
                            Excursao_Id = 31,
                            Data_Fim = new DateTime(2024, 12, 25, 14, 43, 11, 363, DateTimeKind.Utc).AddTicks(2628),
                            Data_Inicio = new DateTime(2024, 12, 25, 9, 43, 11, 363, DateTimeKind.Utc).AddTicks(2627),
                            Descricao = "Passeio pelas trilhas que levam às maiores cataratas do mundo",
                            Preco = 90.0m,
                            Staff_Id = 12,
                            Titulo = "Trilha das Cataratas"
                        },
                        new
                        {
                            Excursao_Id = 32,
                            Data_Fim = new DateTime(2024, 12, 26, 13, 43, 11, 363, DateTimeKind.Utc).AddTicks(2630),
                            Data_Inicio = new DateTime(2024, 12, 26, 9, 43, 11, 363, DateTimeKind.Utc).AddTicks(2629),
                            Descricao = "Aventura subaquática com mergulho em recifes de corais",
                            Preco = 130.0m,
                            Staff_Id = 13,
                            Titulo = "Mergulho em Recife"
                        },
                        new
                        {
                            Excursao_Id = 33,
                            Data_Fim = new DateTime(2024, 12, 27, 14, 43, 11, 363, DateTimeKind.Utc).AddTicks(2632),
                            Data_Inicio = new DateTime(2024, 12, 27, 9, 43, 11, 363, DateTimeKind.Utc).AddTicks(2631),
                            Descricao = "Tour pelas principais atrações históricas da cidade",
                            Preco = 60.0m,
                            Staff_Id = 14,
                            Titulo = "Passeio Histórico"
                        },
                        new
                        {
                            Excursao_Id = 34,
                            Data_Fim = new DateTime(2024, 12, 28, 15, 43, 11, 363, DateTimeKind.Utc).AddTicks(2633),
                            Data_Inicio = new DateTime(2024, 12, 28, 9, 43, 11, 363, DateTimeKind.Utc).AddTicks(2633),
                            Descricao = "Tour histórico pelas antigas missões dos Jesuítas",
                            Preco = 80.0m,
                            Staff_Id = 15,
                            Titulo = "Caminho dos Jesuítas"
                        },
                        new
                        {
                            Excursao_Id = 35,
                            Data_Fim = new DateTime(2024, 12, 29, 13, 43, 11, 363, DateTimeKind.Utc).AddTicks(2637),
                            Data_Inicio = new DateTime(2024, 12, 29, 9, 43, 11, 363, DateTimeKind.Utc).AddTicks(2635),
                            Descricao = "Passeio de bicicleta pelas trilhas montanhosas",
                            Preco = 70.0m,
                            Staff_Id = 16,
                            Titulo = "Ciclismo nas Montanhas"
                        },
                        new
                        {
                            Excursao_Id = 36,
                            Data_Fim = new DateTime(2024, 12, 30, 14, 43, 11, 363, DateTimeKind.Utc).AddTicks(2639),
                            Data_Inicio = new DateTime(2024, 12, 30, 9, 43, 11, 363, DateTimeKind.Utc).AddTicks(2638),
                            Descricao = "Aventura de rafting em um dos rios mais desafiadores",
                            Preco = 110.0m,
                            Staff_Id = 17,
                            Titulo = "Rafting no Rio"
                        },
                        new
                        {
                            Excursao_Id = 37,
                            Data_Fim = new DateTime(2024, 12, 31, 16, 43, 11, 363, DateTimeKind.Utc).AddTicks(2641),
                            Data_Inicio = new DateTime(2024, 12, 31, 9, 43, 11, 363, DateTimeKind.Utc).AddTicks(2640),
                            Descricao = "Experiência gastronômica por diferentes restaurantes locais",
                            Preco = 150.0m,
                            Staff_Id = 18,
                            Titulo = "Tour Gastronômico"
                        },
                        new
                        {
                            Excursao_Id = 38,
                            Data_Fim = new DateTime(2025, 1, 1, 18, 43, 11, 363, DateTimeKind.Utc).AddTicks(2642),
                            Data_Inicio = new DateTime(2025, 1, 1, 9, 43, 11, 363, DateTimeKind.Utc).AddTicks(2642),
                            Descricao = "Caminhada até a cratera de um vulcão ativo",
                            Preco = 180.0m,
                            Staff_Id = 19,
                            Titulo = "Aventura no Vulcão"
                        },
                        new
                        {
                            Excursao_Id = 39,
                            Data_Fim = new DateTime(2025, 1, 2, 17, 43, 11, 363, DateTimeKind.Utc).AddTicks(2644),
                            Data_Inicio = new DateTime(2025, 1, 2, 9, 43, 11, 363, DateTimeKind.Utc).AddTicks(2644),
                            Descricao = "Uma experiência no globo de neve para explorar as regiões geladas",
                            Preco = 220.0m,
                            Staff_Id = 20,
                            Titulo = "Aventura no Globo de Neve"
                        });
                });

            modelBuilder.Entity("ReserveSystem.Models.JobTestModel", b =>
                {
                    b.Property<int>("Job_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Job_ID"));

                    b.Property<string>("Job_Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Job_Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Job_ID");

                    b.ToTable("JobTestModel");
                });

            modelBuilder.Entity("ReserveSystem.Models.ReservaExcursaoModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ClienteId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DataReserva")
                        .HasColumnType("DATETIME");

                    b.Property<int>("ExcursaoId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("NumPessoas")
                        .HasColumnType("int");

                    b.Property<decimal>("ValorTotal")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("ClienteId");

                    b.HasIndex("ExcursaoId");

                    b.ToTable("ReservaExcursaoModel");

                    b.HasData(
                        new
                        {
                            Id = 41,
                            ClienteId = 22,
                            DataReserva = new DateTime(2024, 12, 13, 9, 43, 11, 363, DateTimeKind.Utc).AddTicks(2846),
                            ExcursaoId = 23,
                            NumPessoas = 1,
                            ValorTotal = 50m
                        },
                        new
                        {
                            Id = 42,
                            ClienteId = 33,
                            DataReserva = new DateTime(2024, 12, 14, 9, 43, 11, 363, DateTimeKind.Utc).AddTicks(2852),
                            ExcursaoId = 21,
                            NumPessoas = 4,
                            ValorTotal = 200m
                        },
                        new
                        {
                            Id = 43,
                            ClienteId = 24,
                            DataReserva = new DateTime(2024, 12, 15, 9, 43, 11, 363, DateTimeKind.Utc).AddTicks(2853),
                            ExcursaoId = 25,
                            NumPessoas = 3,
                            ValorTotal = 150m
                        },
                        new
                        {
                            Id = 44,
                            ClienteId = 35,
                            DataReserva = new DateTime(2024, 12, 16, 9, 43, 11, 363, DateTimeKind.Utc).AddTicks(2854),
                            ExcursaoId = 26,
                            NumPessoas = 5,
                            ValorTotal = 250m
                        },
                        new
                        {
                            Id = 45,
                            ClienteId = 36,
                            DataReserva = new DateTime(2024, 12, 17, 9, 43, 11, 363, DateTimeKind.Utc).AddTicks(2855),
                            ExcursaoId = 34,
                            NumPessoas = 2,
                            ValorTotal = 120m
                        },
                        new
                        {
                            Id = 46,
                            ClienteId = 27,
                            DataReserva = new DateTime(2024, 12, 18, 9, 43, 11, 363, DateTimeKind.Utc).AddTicks(2856),
                            ExcursaoId = 27,
                            NumPessoas = 1,
                            ValorTotal = 60m
                        },
                        new
                        {
                            Id = 47,
                            ClienteId = 28,
                            DataReserva = new DateTime(2024, 12, 19, 9, 43, 11, 363, DateTimeKind.Utc).AddTicks(2858),
                            ExcursaoId = 38,
                            NumPessoas = 6,
                            ValorTotal = 300m
                        },
                        new
                        {
                            Id = 48,
                            ClienteId = 29,
                            DataReserva = new DateTime(2024, 12, 20, 9, 43, 11, 363, DateTimeKind.Utc).AddTicks(2859),
                            ExcursaoId = 39,
                            NumPessoas = 3,
                            ValorTotal = 180m
                        },
                        new
                        {
                            Id = 49,
                            ClienteId = 31,
                            DataReserva = new DateTime(2024, 12, 21, 9, 43, 11, 363, DateTimeKind.Utc).AddTicks(2860),
                            ExcursaoId = 32,
                            NumPessoas = 2,
                            ValorTotal = 110m
                        },
                        new
                        {
                            Id = 50,
                            ClienteId = 21,
                            DataReserva = new DateTime(2024, 12, 22, 9, 43, 11, 363, DateTimeKind.Utc).AddTicks(2861),
                            ExcursaoId = 25,
                            NumPessoas = 4,
                            ValorTotal = 200m
                        },
                        new
                        {
                            Id = 51,
                            ClienteId = 32,
                            DataReserva = new DateTime(2024, 12, 23, 9, 43, 11, 363, DateTimeKind.Utc).AddTicks(2862),
                            ExcursaoId = 21,
                            NumPessoas = 1,
                            ValorTotal = 50m
                        },
                        new
                        {
                            Id = 52,
                            ClienteId = 33,
                            DataReserva = new DateTime(2024, 12, 24, 9, 43, 11, 363, DateTimeKind.Utc).AddTicks(2863),
                            ExcursaoId = 33,
                            NumPessoas = 5,
                            ValorTotal = 250m
                        },
                        new
                        {
                            Id = 53,
                            ClienteId = 34,
                            DataReserva = new DateTime(2024, 12, 25, 9, 43, 11, 363, DateTimeKind.Utc).AddTicks(2865),
                            ExcursaoId = 26,
                            NumPessoas = 2,
                            ValorTotal = 120m
                        },
                        new
                        {
                            Id = 54,
                            ClienteId = 35,
                            DataReserva = new DateTime(2024, 12, 26, 9, 43, 11, 363, DateTimeKind.Utc).AddTicks(2866),
                            ExcursaoId = 24,
                            NumPessoas = 3,
                            ValorTotal = 150m
                        },
                        new
                        {
                            Id = 55,
                            ClienteId = 23,
                            DataReserva = new DateTime(2024, 12, 27, 9, 43, 11, 363, DateTimeKind.Utc).AddTicks(2867),
                            ExcursaoId = 37,
                            NumPessoas = 2,
                            ValorTotal = 100m
                        },
                        new
                        {
                            Id = 56,
                            ClienteId = 21,
                            DataReserva = new DateTime(2024, 12, 28, 9, 43, 11, 363, DateTimeKind.Utc).AddTicks(2868),
                            ExcursaoId = 28,
                            NumPessoas = 4,
                            ValorTotal = 200m
                        },
                        new
                        {
                            Id = 57,
                            ClienteId = 28,
                            DataReserva = new DateTime(2024, 12, 29, 9, 43, 11, 363, DateTimeKind.Utc).AddTicks(2869),
                            ExcursaoId = 29,
                            NumPessoas = 6,
                            ValorTotal = 300m
                        },
                        new
                        {
                            Id = 58,
                            ClienteId = 29,
                            DataReserva = new DateTime(2024, 12, 30, 9, 43, 11, 363, DateTimeKind.Utc).AddTicks(2870),
                            ExcursaoId = 22,
                            NumPessoas = 2,
                            ValorTotal = 110m
                        },
                        new
                        {
                            Id = 59,
                            ClienteId = 40,
                            DataReserva = new DateTime(2024, 12, 31, 9, 43, 11, 363, DateTimeKind.Utc).AddTicks(2871),
                            ExcursaoId = 33,
                            NumPessoas = 3,
                            ValorTotal = 150m
                        },
                        new
                        {
                            Id = 60,
                            ClienteId = 21,
                            DataReserva = new DateTime(2024, 12, 12, 9, 43, 11, 363, DateTimeKind.Utc).AddTicks(2872),
                            ExcursaoId = 22,
                            NumPessoas = 2,
                            ValorTotal = 100m
                        });
                });

            modelBuilder.Entity("ReserveSystem.Models.StaffTestModel", b =>
                {
                    b.Property<int>("Staff_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Staff_Id"));

                    b.Property<int>("Job_ID")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Staff_Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Staff_Id");

                    b.ToTable("StaffTestModel");
                });

            modelBuilder.Entity("ReserveSystem.Models.ExcursaoFavoritaModel", b =>
                {
                    b.HasOne("ReserveSystem.Models.ClienteTestModel", "Cliente")
                        .WithMany()
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ReserveSystem.Models.ExcursaoModel", "Excursao")
                        .WithMany()
                        .HasForeignKey("ExcursaoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cliente");

                    b.Navigation("Excursao");
                });

            modelBuilder.Entity("ReserveSystem.Models.ReservaExcursaoModel", b =>
                {
                    b.HasOne("ReserveSystem.Models.ClienteTestModel", "Cliente")
                        .WithMany("ReservaExcursoes")
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ReserveSystem.Models.ExcursaoModel", "Excursao")
                        .WithMany("ReservaExcursoes")
                        .HasForeignKey("ExcursaoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cliente");

                    b.Navigation("Excursao");
                });

            modelBuilder.Entity("ReserveSystem.Models.ClienteTestModel", b =>
                {
                    b.Navigation("ReservaExcursoes");
                });

            modelBuilder.Entity("ReserveSystem.Models.ExcursaoModel", b =>
                {
                    b.Navigation("ReservaExcursoes");
                });
#pragma warning restore 612, 618
        }
    }
}
