// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ReserveSystem.Data;

#nullable disable

namespace ReserveSystem.Migrations
{
    [DbContext(typeof(ReserveSystemContext))]
    [Migration("20250105233219_AddData2")]
    partial class AddData2
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ReserveSystem.Models.ExcursaoModel", b =>
                {
                    b.Property<int>("ExcursaoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ExcursaoId"));

                    b.Property<DateTime>("Data_Fim")
                        .HasColumnType("DATE");

                    b.Property<DateTime>("Data_Inicio")
                        .HasColumnType("DATETIME");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("Preco")
                        .HasColumnType("FLOAT");

                    b.Property<int>("StaffId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("ExcursaoId");

                    b.HasIndex("StaffId");

                    b.ToTable("ExcursaoModel");

                    b.HasData(
                        new
                        {
                            ExcursaoId = 1,
                            Data_Fim = new DateTime(2025, 1, 10, 18, 0, 0, 0, DateTimeKind.Unspecified),
                            Data_Inicio = new DateTime(2025, 1, 10, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            Descricao = "Descubra os principais pontos históricos de Lisboa.",
                            Preco = 50.0,
                            StaffId = 1,
                            Titulo = "Tour Histórico de Lisboa"
                        },
                        new
                        {
                            ExcursaoId = 2,
                            Data_Fim = new DateTime(2025, 1, 12, 17, 0, 0, 0, DateTimeKind.Unspecified),
                            Data_Inicio = new DateTime(2025, 1, 12, 8, 30, 0, 0, DateTimeKind.Unspecified),
                            Descricao = "Explore as melhores vinícolas da região do Douro.",
                            Preco = 75.0,
                            StaffId = 2,
                            Titulo = "Rota dos Vinhos do Douro"
                        },
                        new
                        {
                            ExcursaoId = 3,
                            Data_Fim = new DateTime(2025, 1, 15, 16, 0, 0, 0, DateTimeKind.Unspecified),
                            Data_Inicio = new DateTime(2025, 1, 15, 7, 0, 0, 0, DateTimeKind.Unspecified),
                            Descricao = "Aproveite uma trilha guiada na Serra da Estrela.",
                            Preco = 60.0,
                            StaffId = 3,
                            Titulo = "Caminhada na Serra da Estrela"
                        },
                        new
                        {
                            ExcursaoId = 4,
                            Data_Fim = new DateTime(2025, 1, 18, 13, 0, 0, 0, DateTimeKind.Unspecified),
                            Data_Inicio = new DateTime(2025, 1, 18, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            Descricao = "Uma experiência relaxante navegando pelo Rio Tejo.",
                            Preco = 40.0,
                            StaffId = 4,
                            Titulo = "Passeio de Barco no Rio Tejo"
                        },
                        new
                        {
                            ExcursaoId = 5,
                            Data_Fim = new DateTime(2025, 1, 20, 12, 30, 0, 0, DateTimeKind.Unspecified),
                            Data_Inicio = new DateTime(2025, 1, 20, 9, 30, 0, 0, DateTimeKind.Unspecified),
                            Descricao = "Conheça a história do Mosteiro da Batalha.",
                            Preco = 35.0,
                            StaffId = 5,
                            Titulo = "Visita ao Mosteiro da Batalha"
                        },
                        new
                        {
                            ExcursaoId = 6,
                            Data_Fim = new DateTime(2025, 1, 22, 17, 0, 0, 0, DateTimeKind.Unspecified),
                            Data_Inicio = new DateTime(2025, 1, 22, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            Descricao = "Uma excursão pelos monumentos históricos de Évora.",
                            Preco = 65.0,
                            StaffId = 6,
                            Titulo = "Exploração de Évora"
                        },
                        new
                        {
                            ExcursaoId = 7,
                            Data_Fim = new DateTime(2025, 1, 25, 18, 0, 0, 0, DateTimeKind.Unspecified),
                            Data_Inicio = new DateTime(2025, 1, 25, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            Descricao = "Capture as vistas incríveis da Serra da Arrábida.",
                            Preco = 80.0,
                            StaffId = 7,
                            Titulo = "Safari Fotográfico na Arrábida"
                        },
                        new
                        {
                            ExcursaoId = 8,
                            Data_Fim = new DateTime(2025, 1, 28, 17, 30, 0, 0, DateTimeKind.Unspecified),
                            Data_Inicio = new DateTime(2025, 1, 28, 9, 30, 0, 0, DateTimeKind.Unspecified),
                            Descricao = "Explore os palácios e paisagens de Sintra.",
                            Preco = 70.0,
                            StaffId = 8,
                            Titulo = "Passeio Cultural em Sintra"
                        },
                        new
                        {
                            ExcursaoId = 9,
                            Data_Fim = new DateTime(2025, 1, 30, 14, 0, 0, 0, DateTimeKind.Unspecified),
                            Data_Inicio = new DateTime(2025, 1, 30, 11, 0, 0, 0, DateTimeKind.Unspecified),
                            Descricao = "Descubra a culinária local do Porto.",
                            Preco = 50.0,
                            StaffId = 9,
                            Titulo = "Tour Gastronômico em Porto"
                        },
                        new
                        {
                            ExcursaoId = 10,
                            Data_Fim = new DateTime(2025, 2, 2, 15, 0, 0, 0, DateTimeKind.Unspecified),
                            Data_Inicio = new DateTime(2025, 2, 2, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            Descricao = "Um passeio pelas águas e ilhas da Ria Formosa.",
                            Preco = 60.0,
                            StaffId = 10,
                            Titulo = "Exploração da Ria Formosa"
                        },
                        new
                        {
                            ExcursaoId = 11,
                            Data_Fim = new DateTime(2025, 2, 5, 23, 0, 0, 0, DateTimeKind.Unspecified),
                            Data_Inicio = new DateTime(2025, 2, 5, 19, 0, 0, 0, DateTimeKind.Unspecified),
                            Descricao = "Descubra a magia de Lisboa à noite.",
                            Preco = 45.0,
                            StaffId = 11,
                            Titulo = "Tour Noturno em Lisboa"
                        },
                        new
                        {
                            ExcursaoId = 12,
                            Data_Fim = new DateTime(2025, 2, 7, 12, 30, 0, 0, DateTimeKind.Unspecified),
                            Data_Inicio = new DateTime(2025, 2, 7, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            Descricao = "Visite as Grutas de Mira de Aire e suas formações únicas.",
                            Preco = 30.0,
                            StaffId = 12,
                            Titulo = "Exploração Subterrânea em Mira de Aire"
                        },
                        new
                        {
                            ExcursaoId = 13,
                            Data_Fim = new DateTime(2025, 2, 10, 18, 0, 0, 0, DateTimeKind.Unspecified),
                            Data_Inicio = new DateTime(2025, 2, 10, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            Descricao = "Explore a natureza e a beleza do Parque Nacional Peneda-Gerês.",
                            Preco = 85.0,
                            StaffId = 13,
                            Titulo = "Aventura em Peneda-Gerês"
                        },
                        new
                        {
                            ExcursaoId = 14,
                            Data_Fim = new DateTime(2025, 2, 12, 19, 0, 0, 0, DateTimeKind.Unspecified),
                            Data_Inicio = new DateTime(2025, 2, 12, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            Descricao = "Conheça as aldeias encantadoras e cheias de história.",
                            Preco = 95.0,
                            StaffId = 14,
                            Titulo = "Passeio pelas Aldeias Históricas de Portugal"
                        },
                        new
                        {
                            ExcursaoId = 15,
                            Data_Fim = new DateTime(2025, 2, 15, 15, 0, 0, 0, DateTimeKind.Unspecified),
                            Data_Inicio = new DateTime(2025, 2, 15, 11, 0, 0, 0, DateTimeKind.Unspecified),
                            Descricao = "Um passeio inesquecível pelo Rio Douro.",
                            Preco = 55.0,
                            StaffId = 15,
                            Titulo = "Cruzeiro no Rio Douro"
                        },
                        new
                        {
                            ExcursaoId = 16,
                            Data_Fim = new DateTime(2025, 2, 18, 13, 0, 0, 0, DateTimeKind.Unspecified),
                            Data_Inicio = new DateTime(2025, 2, 18, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            Descricao = "Descubra o Alentejo sobre duas rodas.",
                            Preco = 40.0,
                            StaffId = 16,
                            Titulo = "Passeio de Bicicleta no Alentejo"
                        },
                        new
                        {
                            ExcursaoId = 17,
                            Data_Fim = new DateTime(2025, 2, 20, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            Data_Inicio = new DateTime(2025, 2, 20, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            Descricao = "Siga os passos do grande poeta em Lisboa.",
                            Preco = 25.0,
                            StaffId = 17,
                            Titulo = "Roteiro Literário de Fernando Pessoa"
                        },
                        new
                        {
                            ExcursaoId = 18,
                            Data_Fim = new DateTime(2025, 2, 23, 18, 0, 0, 0, DateTimeKind.Unspecified),
                            Data_Inicio = new DateTime(2025, 2, 23, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            Descricao = "Uma jornada pelos castelos mais icônicos do país.",
                            Preco = 70.0,
                            StaffId = 18,
                            Titulo = "Passeio pelos Castelos de Portugal"
                        },
                        new
                        {
                            ExcursaoId = 19,
                            Data_Fim = new DateTime(2025, 2, 25, 12, 30, 0, 0, DateTimeKind.Unspecified),
                            Data_Inicio = new DateTime(2025, 2, 25, 9, 30, 0, 0, DateTimeKind.Unspecified),
                            Descricao = "Viva uma experiência única no Algarve.",
                            Preco = 50.0,
                            StaffId = 19,
                            Titulo = "Observação de Golfinhos no Algarve"
                        },
                        new
                        {
                            ExcursaoId = 20,
                            Data_Fim = new DateTime(2025, 2, 27, 13, 0, 0, 0, DateTimeKind.Unspecified),
                            Data_Inicio = new DateTime(2025, 2, 27, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            Descricao = "Descubra a vibrante arte de rua de Lisboa.",
                            Preco = 35.0,
                            StaffId = 20,
                            Titulo = "Tour de Arte Urbana em Lisboa"
                        },
                        new
                        {
                            ExcursaoId = 21,
                            Data_Fim = new DateTime(2025, 3, 1, 17, 0, 0, 0, DateTimeKind.Unspecified),
                            Data_Inicio = new DateTime(2025, 3, 1, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            Descricao = "Encante-se com as paisagens da amendoeira em flor.",
                            Preco = 75.0,
                            StaffId = 21,
                            Titulo = "Rota da Amendoeira em Flor"
                        },
                        new
                        {
                            ExcursaoId = 22,
                            Data_Fim = new DateTime(2025, 3, 3, 18, 30, 0, 0, DateTimeKind.Unspecified),
                            Data_Inicio = new DateTime(2025, 3, 3, 8, 30, 0, 0, DateTimeKind.Unspecified),
                            Descricao = "Relaxe nas praias deslumbrantes do Alentejo.",
                            Preco = 65.0,
                            StaffId = 22,
                            Titulo = "Passeio pelas Praias do Alentejo"
                        },
                        new
                        {
                            ExcursaoId = 23,
                            Data_Fim = new DateTime(2025, 3, 5, 12, 30, 0, 0, DateTimeKind.Unspecified),
                            Data_Inicio = new DateTime(2025, 3, 5, 9, 30, 0, 0, DateTimeKind.Unspecified),
                            Descricao = "Explore a rica história e cultura de Coimbra.",
                            Preco = 40.0,
                            StaffId = 23,
                            Titulo = "Tour Histórico em Coimbra"
                        },
                        new
                        {
                            ExcursaoId = 24,
                            Data_Fim = new DateTime(2025, 3, 7, 15, 0, 0, 0, DateTimeKind.Unspecified),
                            Data_Inicio = new DateTime(2025, 3, 7, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            Descricao = "Uma experiência nas furnas vulcânicas de São Miguel.",
                            Preco = 50.0,
                            StaffId = 24,
                            Titulo = "Visita às Furnas de São Miguel"
                        },
                        new
                        {
                            ExcursaoId = 25,
                            Data_Fim = new DateTime(2025, 3, 10, 18, 0, 0, 0, DateTimeKind.Unspecified),
                            Data_Inicio = new DateTime(2025, 3, 10, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            Descricao = "Uma excursão marítima inesquecível nas Berlengas.",
                            Preco = 80.0,
                            StaffId = 25,
                            Titulo = "Jornada pelas Ilhas Berlengas"
                        });
                });

            modelBuilder.Entity("ReserveSystem.Models.PrecarioModel", b =>
                {
                    b.Property<int>("PrecoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PrecoId"));

                    b.Property<DateTime>("Data_Inicio")
                        .HasColumnType("datetime2");

                    b.Property<int>("ExcursaoId")
                        .HasColumnType("INTEGER");

                    b.Property<float>("Preco")
                        .HasColumnType("real");

                    b.HasKey("PrecoId");

                    b.HasIndex("ExcursaoId");

                    b.ToTable("PrecarioModel");
                });

            modelBuilder.Entity("ReserveSystem.Models.StaffModel", b =>
                {
                    b.Property<int>("StaffId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StaffId"));

                    b.Property<string>("Job_Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Staff_Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("StaffId");

                    b.ToTable("StaffModel");

                    b.HasData(
                        new
                        {
                            StaffId = 1,
                            Job_Name = "Motorista",
                            Staff_Name = "João Silva"
                        },
                        new
                        {
                            StaffId = 2,
                            Job_Name = "Gestor de Excursão",
                            Staff_Name = "Maria Oliveira"
                        },
                        new
                        {
                            StaffId = 3,
                            Job_Name = "Guia Turistico",
                            Staff_Name = "Carlos Santos"
                        },
                        new
                        {
                            StaffId = 4,
                            Job_Name = "Motorista",
                            Staff_Name = "Ana Souza"
                        },
                        new
                        {
                            StaffId = 5,
                            Job_Name = "Gestor de Excursão",
                            Staff_Name = "Pedro Almeida"
                        },
                        new
                        {
                            StaffId = 6,
                            Job_Name = "Guia Turistico",
                            Staff_Name = "Luciana Costa"
                        },
                        new
                        {
                            StaffId = 7,
                            Job_Name = "Motorista",
                            Staff_Name = "Rafael Gomes"
                        },
                        new
                        {
                            StaffId = 8,
                            Job_Name = "Gestor de Excursão",
                            Staff_Name = "Fernanda Carvalho"
                        },
                        new
                        {
                            StaffId = 9,
                            Job_Name = "Guia Turistico",
                            Staff_Name = "Ricardo Pereira"
                        },
                        new
                        {
                            StaffId = 10,
                            Job_Name = "Motorista",
                            Staff_Name = "Juliana Mendes"
                        },
                        new
                        {
                            StaffId = 11,
                            Job_Name = "Gestor de Excursão",
                            Staff_Name = "Gustavo Rocha"
                        },
                        new
                        {
                            StaffId = 12,
                            Job_Name = "Guia Turistico",
                            Staff_Name = "Camila Ribeiro"
                        },
                        new
                        {
                            StaffId = 13,
                            Job_Name = "Motorista",
                            Staff_Name = "André Lima"
                        },
                        new
                        {
                            StaffId = 14,
                            Job_Name = "Gestor de Excursão",
                            Staff_Name = "Patrícia Fonseca"
                        },
                        new
                        {
                            StaffId = 15,
                            Job_Name = "Guia Turistico",
                            Staff_Name = "Tiago Martins"
                        },
                        new
                        {
                            StaffId = 16,
                            Job_Name = "Motorista",
                            Staff_Name = "Letícia Freitas"
                        },
                        new
                        {
                            StaffId = 17,
                            Job_Name = "Gestor de Excursão",
                            Staff_Name = "Bruno Vieira"
                        },
                        new
                        {
                            StaffId = 18,
                            Job_Name = "Guia Turistico",
                            Staff_Name = "Sara Fernandes"
                        },
                        new
                        {
                            StaffId = 19,
                            Job_Name = "Motorista",
                            Staff_Name = "Rodrigo Lopes"
                        },
                        new
                        {
                            StaffId = 20,
                            Job_Name = "Gestor de Excursão",
                            Staff_Name = "Natália Correia"
                        },
                        new
                        {
                            StaffId = 21,
                            Job_Name = "Guia Turistico",
                            Staff_Name = "Eduardo Cardoso"
                        },
                        new
                        {
                            StaffId = 22,
                            Job_Name = "Motorista",
                            Staff_Name = "Carolina Neves"
                        },
                        new
                        {
                            StaffId = 23,
                            Job_Name = "Gestor de Excursão",
                            Staff_Name = "Diego Farias"
                        },
                        new
                        {
                            StaffId = 24,
                            Job_Name = "Guia Turistico",
                            Staff_Name = "Vanessa Moreira"
                        },
                        new
                        {
                            StaffId = 25,
                            Job_Name = "Motorista",
                            Staff_Name = "Felipe Azevedo"
                        });
                });

            modelBuilder.Entity("ReserveSystem.Models.ExcursaoModel", b =>
                {
                    b.HasOne("ReserveSystem.Models.StaffModel", "Staff")
                        .WithMany("Excursao")
                        .HasForeignKey("StaffId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Staff");
                });

            modelBuilder.Entity("ReserveSystem.Models.PrecarioModel", b =>
                {
                    b.HasOne("ReserveSystem.Models.ExcursaoModel", "Excursao")
                        .WithMany("Precario")
                        .HasForeignKey("ExcursaoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Excursao");
                });

            modelBuilder.Entity("ReserveSystem.Models.ExcursaoModel", b =>
                {
                    b.Navigation("Precario");
                });

            modelBuilder.Entity("ReserveSystem.Models.StaffModel", b =>
                {
                    b.Navigation("Excursao");
                });
#pragma warning restore 612, 618
        }
    }
}
