// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ReserveSystem.Data;

#nullable disable

namespace ReserveSystem.Migrations
{
    [DbContext(typeof(ReserveSystemContext))]
    [Migration("20250109220453_UpdateTables")]
    partial class UpdateTables
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ReserveSystem.Models.Job", b =>
                {
                    b.Property<int>("Job_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Job_ID"));

                    b.Property<string>("Job_Description")
                        .HasMaxLength(350)
                        .HasColumnType("nvarchar(350)");

                    b.Property<string>("Job_Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("Job_ID");

                    b.ToTable("Job");
                });

            modelBuilder.Entity("ReserveSystem.Models.RoomService", b =>
                {
                    b.Property<int>("ID_Room_Service")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID_Room_Service"));

                    b.Property<int>("Job_ID")
                        .HasColumnType("int");

                    b.Property<bool>("Room_Service_Active")
                        .HasColumnType("bit");

                    b.Property<string>("Room_Service_Description")
                        .HasMaxLength(350)
                        .HasColumnType("nvarchar(350)");

                    b.Property<string>("Room_Service_Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("ID_Room_Service");

                    b.HasIndex("Job_ID");

                    b.ToTable("RoomService");
                });

            modelBuilder.Entity("ReserveSystem.Models.RoomServicePrice", b =>
                {
                    b.Property<int>("ID_Room_Service_Price")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID_Room_Service_Price"));

                    b.Property<DateTime?>("End_Date")
                        .IsRequired()
                        .HasColumnType("datetime2");

                    b.Property<int>("ID_Room_Service")
                        .HasColumnType("int");

                    b.Property<double>("Room_Service_Price")
                        .HasColumnType("float");

                    b.Property<DateTime>("Start_Date")
                        .HasColumnType("datetime2");

                    b.HasKey("ID_Room_Service_Price");

                    b.HasIndex("ID_Room_Service");

                    b.ToTable("RoomServicePrice");
                });

            modelBuilder.Entity("ReserveSystem.Models.RoomService", b =>
                {
                    b.HasOne("ReserveSystem.Models.Job", "Job")
                        .WithMany()
                        .HasForeignKey("Job_ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Job");
                });

            modelBuilder.Entity("ReserveSystem.Models.RoomServicePrice", b =>
                {
                    b.HasOne("ReserveSystem.Models.RoomService", "RoomService")
                        .WithMany()
                        .HasForeignKey("ID_Room_Service")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RoomService");
                });
#pragma warning restore 612, 618
        }
    }
}
