// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ReserveSystem.Data;

#nullable disable

namespace ReserveSystem.Migrations
{
    [DbContext(typeof(ReserveSystemContext))]
    partial class ReserveSystemContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.11");

            modelBuilder.Entity("ReserveSystem.Models.ClienteModel", b =>
                {
                    b.Property<int>("ClienteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(8000)
                        .HasColumnType("TEXT");

                    b.Property<string>("MoradaCliente")
                        .IsRequired()
                        .HasMaxLength(8000)
                        .HasColumnType("TEXT");

                    b.Property<string>("NomeCliente")
                        .IsRequired()
                        .HasMaxLength(8000)
                        .HasColumnType("TEXT");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(8000)
                        .HasColumnType("TEXT");

                    b.Property<string>("Telefone")
                        .IsRequired()
                        .HasMaxLength(8000)
                        .HasColumnType("TEXT");

                    b.HasKey("ClienteId");

                    b.ToTable("ClienteModel");
                });

            modelBuilder.Entity("ReserveSystem.Models.Equipamento", b =>
                {
                    b.Property<int>("IdEquipamento")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("NomeEquipamento")
                        .IsRequired()
                        .HasMaxLength(8000)
                        .HasColumnType("TEXT");

                    b.Property<int>("Quantidade")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TipoEquipamento")
                        .IsRequired()
                        .HasMaxLength(8000)
                        .HasColumnType("TEXT");

                    b.HasKey("IdEquipamento");

                    b.ToTable("Equipamento");
                });

            modelBuilder.Entity("ReserveSystem.Models.ReservaModel", b =>
                {
                    b.Property<int>("ReservaID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ClienteId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DataFim")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DataInicio")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DataReserva")
                        .HasColumnType("TEXT");

                    b.Property<int>("Partcipantes")
                        .HasColumnType("INTEGER");

                    b.Property<double>("PrecoTotal")
                        .HasColumnType("REAL");

                    b.Property<string>("TipoReserva")
                        .IsRequired()
                        .HasMaxLength(8000)
                        .HasColumnType("TEXT");

                    b.HasKey("ReservaID");

                    b.HasIndex("ClienteId");

                    b.ToTable("ReservaModel");
                });

            modelBuilder.Entity("ReserveSystem.Models.Sala", b =>
                {
                    b.Property<long>("IdSala")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<TimeOnly>("HoraFim")
                        .HasColumnType("TEXT");

                    b.Property<TimeOnly>("HoraInicio")
                        .HasColumnType("TEXT");

                    b.Property<long>("IdTipoSala")
                        .HasColumnType("INTEGER");

                    b.Property<TimeSpan>("TempoPreparação")
                        .HasColumnType("TEXT");

                    b.HasKey("IdSala");

                    b.HasIndex("IdTipoSala");

                    b.ToTable("Sala");
                });

            modelBuilder.Entity("ReserveSystem.Models.TipoSala", b =>
                {
                    b.Property<long>("IdTipoSala")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Capacidade")
                        .HasColumnType("INTEGER");

                    b.Property<string>("NomeSala")
                        .IsRequired()
                        .HasMaxLength(8000)
                        .HasColumnType("TEXT");

                    b.Property<double>("PreçoHora")
                        .HasColumnType("REAL");

                    b.Property<int>("TamanhoSala")
                        .HasColumnType("INTEGER");

                    b.HasKey("IdTipoSala");

                    b.ToTable("TipoSala");
                });

            modelBuilder.Entity("ReserveSystem.Models.ReservaModel", b =>
                {
                    b.HasOne("ReserveSystem.Models.ClienteModel", "Cliente")
                        .WithMany("Reserva")
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cliente");
                });

            modelBuilder.Entity("ReserveSystem.Models.Sala", b =>
                {
                    b.HasOne("ReserveSystem.Models.TipoSala", "TipoSala")
                        .WithMany("Salas")
                        .HasForeignKey("IdTipoSala")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TipoSala");
                });

            modelBuilder.Entity("ReserveSystem.Models.ClienteModel", b =>
                {
                    b.Navigation("Reserva");
                });

            modelBuilder.Entity("ReserveSystem.Models.TipoSala", b =>
                {
                    b.Navigation("Salas");
                });
#pragma warning restore 612, 618
        }
    }
}
