// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ReserveSystem.Data;

#nullable disable

namespace ReserveSystem.Migrations.ReserveSystem
{
    [DbContext(typeof(ReserveSystemContext))]
    [Migration("20241119185808_UpdateRoomServicesBookingModel")]
    partial class UpdateRoomServicesBookingModel
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0");

            modelBuilder.Entity("ReserveSystem.Models.Client", b =>
                {
                    b.Property<int>("ClientId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClientName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("ClientId");

                    b.ToTable("Client");
                });

            modelBuilder.Entity("ReserveSystem.Models.Room", b =>
                {
                    b.Property<int>("RoomId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("RoomName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("RoomId");

                    b.ToTable("Room");
                });

            modelBuilder.Entity("ReserveSystem.Models.RoomService", b =>
                {
                    b.Property<int>("RoomServiceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ServiceName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("RoomServiceId");

                    b.ToTable("RoomService");
                });

            modelBuilder.Entity("ReserveSystem.Models.RoomServicesBooking", b =>
                {
                    b.Property<int>("RoomServiceBookingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("AmountToPay")
                        .HasColumnType("amount_to_pay");

                    b.Property<bool>("BookedState")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("booked_state");

                    b.Property<int?>("ClientFeedback")
                        .HasColumnType("client_feedback");

                    b.Property<int>("ClientId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DateTime")
                        .HasColumnType("date_time");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("end_date");

                    b.Property<bool>("PaymentMade")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("payment_made");

                    b.Property<int>("RoomId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RoomServiceId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("StaffConfirmation")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("staff_confirmation");

                    b.Property<int>("StaffId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("start_date");

                    b.HasKey("RoomServiceBookingId");

                    b.HasIndex("ClientId");

                    b.HasIndex("RoomId");

                    b.HasIndex("RoomServiceId");

                    b.HasIndex("StaffId");

                    b.ToTable("RoomServiceBooking");
                });

            modelBuilder.Entity("ReserveSystem.Models.Staff", b =>
                {
                    b.Property<int>("StaffId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("StaffName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("StaffId");

                    b.ToTable("Staff");
                });

            modelBuilder.Entity("ReserveSystem.Models.RoomServicesBooking", b =>
                {
                    b.HasOne("ReserveSystem.Models.Client", "Client")
                        .WithMany()
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ReserveSystem.Models.Room", "Room")
                        .WithMany()
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ReserveSystem.Models.RoomService", "RoomService")
                        .WithMany()
                        .HasForeignKey("RoomServiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ReserveSystem.Models.Staff", "Staff")
                        .WithMany()
                        .HasForeignKey("StaffId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Client");

                    b.Navigation("Room");

                    b.Navigation("RoomService");

                    b.Navigation("Staff");
                });
#pragma warning restore 612, 618
        }
    }
}
